### PR TITLE
#41 Do not stop timer on the exception thrown by the timer task

### LINKED ISSUE #41: Timer already cancelled error
Occasionally I get the following error in the log:

nats streaming timer issue

Is it known issue in the NATS streaming client, or what could be cause of this issue, and is it possible to recover from this? Re-create the connection? 

#40 might be related

### PR DESCRIPTION
**Pull request by zshamrock**
Was trying to resolve #41. As discussed with @kozlovic wrapping `processAckTimeout` with `try/catch` should prevent the timer be stopped.

Although by making the corresponding change makes `ITConnectionTest::testRaceAckOnClose` to fail. Which also probably explains the reason why the timer task actually threw an exception (so based on the test name, it is indeed looks like due to the race condition). 

I've also observed (see in the changes made), that in the case of the race condition the returned `ackClosure` was null, and so `NPE` was thrown.

Again, this PR is not ready to be merged, as I don't know how to fix `ITConnectionTest::testRaceAckOnClose`, but maybe it will be a starting point for the maintainers to move it further (and maybe the better fix would be to avoid race condition at all? or use `Executors`?, as I am not yet familiar with the internals of the NATS streaming protocol to feel confident to make the corresponding changes).

@kozlovic @mcqueary any thoughts?

### CODE REVIEW

File: src/main/java/io/nats/streaming/StreamingConnectionImpl.java [hunk 1]
```diff
@@ -552,14 +552,25 @@ protected void processAck(Message msg) {
...
+                    cancel();
+                }
             }
         };
         return task;
     }
 
     protected void processAckTimeout(String guid) {
         AckClosure ackClosure = removeAck(guid);
+        if (ackClosure == null) {
```
Comment (zshamrock) [inline src/main/java/io/nats/streaming/StreamingConnectionImpl.java]: I observed while debugging the `ITConnectionTest::testRaceAckOnClose`, that `ackClosure` returned from `removeAck` if waiting long enough in the breakpoint was `null`, and `NPE` was thrown by the line below.

Comment (kozlovic) [inline src/main/java/io/nats/streaming/StreamingConnectionImpl.java]: Indeed, the code should check if `ackClosure` is `null` and if so, simply return. It means that the connection has received the publisher ack from the server and started to process it (removed from the map) and has or will invoke the ack handler callback or notify the synchronous publish call.

We have the same problem in Go (I am going to create an issue/fix for that), except that in Go there won't be an issue with the ack closure being null because the publish call use a function closure for the timer and the ack structure is used there. It is wrong though, since we should get the ack from the `removeAck()` call that ensures that only one thread/go routine gets to the pub ack.

Comment (kozlovic) [inline src/main/java/io/nats/streaming/StreamingConnectionImpl.java]: For info, this is for the Go client: https://github.com/nats-io/go-nats-streaming/pull/131

Comment (zshamrock) [inline src/main/java/io/nats/streaming/StreamingConnectionImpl.java]: Thank you, @kozlovic. And what will be the next step? When the new version of the Java NATS streaming client will be released (with some of the issues fixed)?

**Comment by mcqueary** [comment]
Looking at this now. Thanks.

**Comment by zshamrock** [comment]
Hi, @mcqueary. Nice to hear back from you! Could you, please, also take a look into this one https://github.com/nats-io/java-nats-streaming/pull/45?

File: src/main/java/io/nats/streaming/StreamingConnectionImpl.java [hunk 2]
```diff
@@ -552,14 +552,25 @@ protected void processAck(Message msg) {
...
+            logger.warn("stan: no ack available, could be due to the race condition");
```
Comment (kozlovic) [inline src/main/java/io/nats/streaming/StreamingConnectionImpl.java]: Not sure we need to log anything here. The "race" is not the result of a bug but a fact of life: the timer may expire and fire the callback at the same time that the ack is received and processed on another thread. We need to not process it twice for sure by returning here, but no need to log.

Comment (ColinSullivan1) [inline src/main/java/io/nats/streaming/StreamingConnectionImpl.java]: Agreed here.

**Comment by ColinSullivan1** [comment]
@zshamrock - I'll look at the test.

**Comment by zshamrock** [comment]
Thank you, guys.

Also in order to make the official next release for the streaming client, you need to make the next official release for the java NATS client, as the streaming client depends on some of the changes done in the latest SNAPSHOT of the NATS client, which has to be released first, which probably make the work a little bit more harder.

File: src/main/java/io/nats/streaming/StreamingConnectionImpl.java (hunk 2 above)
Comment (zshamrock) [inline src/main/java/io/nats/streaming/StreamingConnectionImpl.java]: Agree.

File: src/main/java/io/nats/streaming/StreamingConnectionImpl.java [hunk 3]
```diff
@@ -568,7 +568,6 @@ public void run() {
     protected void processAckTimeout(String guid) {
         AckClosure ackClosure = removeAck(guid);
         if (ackClosure == null) {
-            logger.warn("stan: no ack available, could be due to the race condition");
```
Comment (ColinSullivan1) [inline src/main/java/io/nats/streaming/StreamingConnectionImpl.java]: LGTM.

**Comment by ColinSullivan1** [comment]
@zshamrock , Thanks, we really appreciate the contribution and are certainly happy to help.  How is ITConnectionTest::testRaceAckOnClose failing for you?

**Comment by zshamrock** [comment]
If running from IDEA with the fix proposed the test fails with timeout exception:
```
[TEST START] testRaceAckOnClose
[TEST ENDED] Time elapsed: 5.041 sec

org.junit.runners.model.TestTimedOutException: test timed out after 5000 milliseconds

	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1465)
	at io.nats.client.ConnectionImpl.shutdownAndAwaitTermination(ConnectionImpl.java:648)
	at io.nats.client.ConnectionImpl.close(ConnectionImpl.java:637)
	at io.nats.client.ConnectionImpl.close(ConnectionImpl.java:539)
	at io.nats.streaming.StreamingConnectionImpl.close(StreamingConnectionImpl.java:263)
	at io.nats.streaming.ITConnectionTest.testRaceAckOnClose(ITConnectionTest.java:1917)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

Although if I comment the fix, test then is passed from IDEA.

**Comment by zshamrock** [comment]
Although if running from CLI `mvn -Pintegration-test clean verify`, all IT tests are passed, including the one above.

**Comment by ColinSullivan1** [comment]
Hmm.  Mine is passing in the IDE with your fix, so it could be an issue of the test taking longer in that environment.  However, I'm concerned about a deadlock someplace (not in your PR though).  What happens if you increase the test timeout to something larger?
e.g.
```
@Test(timeout = 30000)
public void testRaceAckOnClose() throws Exception {
...
```

**Comment by mcqueary** [comment]
Interesting, I'm using IDEA also and I've not run into any timing issues in the IDE vs CLI in other tests. @ColinSullivan1 suggestion is a good one.

**Comment by zshamrock** [comment]
Indeed could be due to my machine being slower.

I set the timeout to 30_000, and the test passed from IDEA

```
TEST START] testRaceAckOnClose
23:24:17.868 [Time-limited test] ERROR io.nats.client.ConnectionImpl - jnats-subscriptions did not terminate
[TEST ENDED] Time elapsed: 14.245 sec
```

**Comment by ColinSullivan1** [comment]
@zshamrock , thank you for the validation there.  This PR looks good to me; we'll merge.  And thanks again for the contribution!
